"""Regenerate ICVSP_train.ipynb from the files in this folder.

The notebook embeds the project scripts with %%writefile so it runs on Colab without Google
Drive access. Run this after editing any script or config, so the notebook never drifts.

Usage:  python scripts/build_notebook.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EMBED = ['requirements.txt', 'configs/classes.yaml', 'scripts/download_sbp.py', 'scripts/merge_datasets.py',
         'scripts/train.py', 'scripts/evaluate.py', 'scripts/predict_clips.py', 'scripts/extract_frames.py']

CHECK_CLASSES = '''import random, pathlib
import matplotlib.pyplot as plt, matplotlib.patches as patches
from PIL import Image
root = pathlib.Path('/content/raw/sbp_yolo/train')
by_class = {0: [], 1: []}
for lab in root.glob('labels/*.txt'):
    for ln in lab.read_text().splitlines():
        c = int(ln.split()[0])
        if c in by_class and len(by_class[c]) < 50:
            by_class[c].append(lab)
fig, axes = plt.subplots(2, 3, figsize=(15, 8))
for row, c in enumerate(by_class):
    for ax, lab in zip(axes[row], random.sample(by_class[c], 3)):
        img = Image.open(root / 'images' / (lab.stem + '.jpg')); w, h = img.size
        ax.imshow(img); ax.axis('off'); ax.set_title(f'class {c}')
        for ln in lab.read_text().splitlines():
            k, x, y, bw, bh = map(float, ln.split()[:5])
            if int(k) == c:
                ax.add_patch(patches.Rectangle(((x - bw / 2) * w, (y - bh / 2) * h), bw * w, bh * h,
                                               fill=False, color='red', lw=2))
plt.tight_layout(); plt.show()'''

CELLS = [
    ('md', '''# ICVSP: pothole & speed-bump detector (merge → train → evaluate)

**No Google Drive access needed.** This notebook asks for no Google permissions:
- the project scripts are written into the Colab machine by the cells below,
- the public SBP-YOLO dataset is downloaded without signing in,
- results are downloaded to your computer as a zip at the end.

**To run:** Runtime → Change runtime type → **T4 GPU**, then **Runtime → Run all**.
Class IDs were verified on 29 Sep (0 = pothole, 1 = speed bump).

Everything on the Colab machine is deleted when the session ends, so **download the results zip (last cell) before closing**.

_Generated by `scripts/build_notebook.py`. Edit the files in `ICVSP/ai/` and regenerate; do not edit the embedded copies below._'''),
    ('md', '## 1. Check the GPU and set up the project folder'),
    ('code', '!nvidia-smi -L\n%mkdir -p /content/ai/scripts /content/ai/configs /content/ai/runs\n%cd /content/ai'),
    ('md', '## 2. Project scripts'),
    *[('code', f'%%writefile /content/ai/{f}\n' + (ROOT / f).read_text()) for f in EMBED],
    ('md', '## 2b. Install packages (every new session; takes about a minute)'),
    ('code', '!pip -q install -r /content/ai/requirements.txt\nimport ultralytics; print("ultralytics", ultralytics.__version__, "installed")'),
    ('md', '''## 3. Download SBP-YOLO (7,375 images + labels, public, no sign-in)
Takes roughly 10–20 minutes. If it reports failed files (usually Drive rate limits), just run the cell again; it only fetches what is missing.'''),
    ('code', '!python scripts/download_sbp.py --out /content/raw/sbp_yolo\n!du -sh /content/raw/sbp_yolo'),
    ('md', '''## 4. ⚠️ Check the class IDs (do this once)
SBP-YOLO ships without class names. `configs/classes.yaml` assumes **class 0 = pothole, class 1 = speed bump**.
Look at the red boxes below. If the rows are the other way round, swap the two names under `sources: sbp_yolo` in the classes.yaml cell above, re-run that cell, then continue.'''),
    ('code', CHECK_CLASSES),
    ('md', '## 5. Merge into the unified classes (`pothole`, `speed_bump`)\nCheck the report: every source class must map to the right unified class.'),
    ('code', '!python scripts/merge_datasets.py --raw /content/raw --out /content/merged'),
    ('md', """## 6. Experiments
Run **one experiment per Colab session** (free sessions time out). Each new session: run steps 1–5 again (about 20 min), then one experiment below, then step 9 to download.

| Run | What changes | Time on a T4 | Status |
|---|---|---|---|
| v0_public_merge | baseline: 50 epochs, 640 px | ~1 h | ✅ done 29 Sep |
| v1_e150 | train longer: 150 epochs | ~3 h | |
| v2_e150_960 | + bigger images (960 px) for small potholes | ~6 h, may need Colab Pro or 2 sessions | |"""),
    ('md', '### 6a. v0 baseline (done, kept for reference; uncomment only to reproduce)'),
    ('code', '# !python scripts/train.py --data /content/merged/data.yaml --device 0 --batch 32 --epochs 50 --name v0_public_merge\n# !python scripts/evaluate.py --weights runs/v0_public_merge/weights/best.pt --device 0 --public-data /content/merged/data.yaml'),
    ('md', '### 6b. v1: 150 epochs\nThe baseline was still improving at epoch 50. `patience 30` stops early if nothing improves for 30 epochs.'),
    ('code', "import pathlib\nassert pathlib.Path('/content/merged/data.yaml').exists(), 'Run steps 3-5 (download + merge) in this session first.'\n"
             '!python scripts/train.py --data /content/merged/data.yaml --device 0 --batch 32 --epochs 150 --patience 30 --name v1_e150\n!python scripts/evaluate.py --weights runs/v1_e150/weights/best.pt --device 0 --public-data /content/merged/data.yaml'),
    ('md', '### 6c. v2: 150 epochs at 960 px\nHelps small, distant potholes, but runs about 2× slower on the device too; the Hailo speed test decides if it is usable.'),
    ('code', '# Run in its own session: uncomment both lines, and comment out the v1 cell above.\n# !python scripts/train.py --data /content/merged/data.yaml --device 0 --batch 16 --epochs 150 --patience 30 --imgsz 960 --name v2_e150_960\n# !python scripts/evaluate.py --weights runs/v2_e150_960/weights/best.pt --device 0 --imgsz 960 --public-data /content/merged/data.yaml'),
    ('md', '## 7. (Done) Learning curve\nAlready run on 29 Sep (25/50/75 %). Uncomment only to reproduce.'),
    ('code', '# for f in (0.25, 0.5, 0.75):\n#     !python scripts/train.py --data /content/merged/data.yaml --device 0 --batch 32 --epochs 50 --fraction {f}'),
    ('md', '## 8. Download the results\nTrained models, metrics, confusion matrices and merge report (not the dataset, not the clip videos). Unzip into `ICVSP/ai/` and run `python scripts/compare_runs.py` to add the run to `results/experiments.md`.'),
    ('code', """!cp /content/merged/merge_report.json runs/ 2>/dev/null; cd /content/ai && zip -qr /content/icvsp_results.zip runs -x 'runs/egypt_clips/*'
from google.colab import files
files.download('/content/icvsp_results.zip')"""),
    ('md', """## 9. Quick check on Egyptian clips
Shows what the model detects on your own phone clips: boxes drawn on each video, plus `summary.csv` with when it saw a bump.

⚠️ This is a **visual sanity check, not a measurement**: it shows detections but not what the model missed. The real accuracy numbers come from labelling frames (README, step 3).

This step only needs steps 1–2, not the dataset download. Upload the clips (1080p, short) when asked. It uses the model trained in this session if there is one; otherwise upload a `best.pt` from `ICVSP/ai/runs/<run>/weights/`."""),
    ('code', """import pathlib, shutil
from google.colab import files
clips = pathlib.Path('/content/ai/data/egypt_test/clips'); clips.mkdir(parents=True, exist_ok=True)
print('Select your clips:')
for name in files.upload():
    shutil.move(name, clips / name)
trained = sorted(pathlib.Path('/content/ai/runs').glob('v*/weights/best.pt'))
if trained:
    WEIGHTS = str(trained[-1])
else:
    print('No model trained in this session. Select a best.pt:')
    WEIGHTS = '/content/ai/' + next(iter(files.upload()))
print('Using', WEIGHTS)
!python scripts/predict_clips.py --weights "$WEIGHTS" --conf 0.25
!cd /content/ai/runs && zip -qr /content/egypt_clips_check.zip egypt_clips
files.download('/content/egypt_clips_check.zip')"""),
]


def main():
    nb = {'cells': [], 'nbformat': 4, 'nbformat_minor': 0,
          'metadata': {'accelerator': 'GPU', 'colab': {'provenance': []},
                       'kernelspec': {'name': 'python3', 'display_name': 'Python 3'}}}
    for kind, src in CELLS:
        cell = {'cell_type': 'markdown' if kind == 'md' else 'code', 'metadata': {}, 'source': src.splitlines(True)}
        if kind == 'code':
            cell.update(execution_count=None, outputs=[])
        nb['cells'].append(cell)
    (ROOT / 'ICVSP_train.ipynb').write_text(json.dumps(nb, indent=1))
    print(f'ICVSP_train.ipynb: {len(CELLS)} cells')


if __name__ == '__main__':
    main()
