"""Regenerate the training notebooks from the files in this folder.

ICVSP_train.ipynb         Google Colab, interactive (no Google Drive access).
ICVSP_train_kaggle.ipynb  Kaggle, runs unattended with "Save & Run All"; outputs are kept.

Both embed the project scripts with %%writefile. Run this after editing any script or config,
so the notebooks never drift.

Usage:  python scripts/build_notebook.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EMBED = ['requirements.txt', 'configs/classes.yaml', 'scripts/download_sbp.py', 'scripts/merge_datasets.py',
         'scripts/train.py', 'scripts/evaluate.py', 'scripts/predict_clips.py', 'scripts/extract_frames.py',
         'scripts/prelabel.py', 'scripts/prepare_egypt_test.py', 'scripts/make_night.py']

CHECK_CLASSES = '''import random, pathlib
import matplotlib.pyplot as plt, matplotlib.patches as patches
from PIL import Image
root = pathlib.Path('/content/raw/sbp_yolo/train')
by_class = {0: [], 1: []}
for lab in root.glob('labels/*.txt'):
    for ln in lab.read_text().splitlines():
        c = int(ln.split()[0])
        if c in by_class and len(by_class[c]) < 50:
            by_class[c].append(lab)
fig, axes = plt.subplots(2, 3, figsize=(15, 8))
for row, c in enumerate(by_class):
    for ax, lab in zip(axes[row], random.sample(by_class[c], 3)):
        img = Image.open(root / 'images' / (lab.stem + '.jpg')); w, h = img.size
        ax.imshow(img); ax.axis('off'); ax.set_title(f'class {c}')
        for ln in lab.read_text().splitlines():
            k, x, y, bw, bh = map(float, ln.split()[:5])
            if int(k) == c:
                ax.add_patch(patches.Rectangle(((x - bw / 2) * w, (y - bh / 2) * h), bw * w, bh * h,
                                               fill=False, color='red', lw=2))
plt.tight_layout(); plt.show()'''

CELLS = [
    ('md', '''# ICVSP: pothole & speed-bump detector (merge → train → evaluate)

**No Google Drive access needed.** This notebook asks for no Google permissions:
- the project scripts are written into the Colab machine by the cells below,
- the public SBP-YOLO dataset is downloaded without signing in,
- results are downloaded to your computer as a zip at the end.

**To run:** Runtime → Change runtime type → **T4 GPU**, then **Runtime → Run all**.
Class IDs were verified on 29 Sep (0 = pothole, 1 = speed bump).

Everything on the Colab machine is deleted when the session ends, so **download the results zip (last cell) before closing**.

_Generated by `scripts/build_notebook.py`. Edit the files in `ICVSP/ai/` and regenerate; do not edit the embedded copies below._'''),
    ('md', '## 1. Check the GPU and set up the project folder'),
    ('code', '!nvidia-smi -L\n%mkdir -p /content/ai/scripts /content/ai/configs /content/ai/runs\n%cd /content/ai'),
    ('md', '## 2. Project scripts'),
    *[('code', f'%%writefile /content/ai/{f}\n' + (ROOT / f).read_text()) for f in EMBED],
    ('md', '## 2b. Install packages (every new session; takes about a minute)'),
    ('code', '!pip -q install -r /content/ai/requirements.txt\nimport ultralytics; print("ultralytics", ultralytics.__version__, "installed")'),
    ('md', '''## 3. Download SBP-YOLO (7,375 images + labels, public, no sign-in)
Takes roughly 10–20 minutes. If it reports failed files (usually Drive rate limits), just run the cell again; it only fetches what is missing.'''),
    ('code', '!python scripts/download_sbp.py --out /content/raw/sbp_yolo\n!du -sh /content/raw/sbp_yolo'),
    ('md', '''## 4. ⚠️ Check the class IDs (do this once)
SBP-YOLO ships without class names. `configs/classes.yaml` assumes **class 0 = pothole, class 1 = speed bump**.
Look at the red boxes below. If the rows are the other way round, swap the two names under `sources: sbp_yolo` in the classes.yaml cell above, re-run that cell, then continue.'''),
    ('code', CHECK_CLASSES),
    ('md', '## 5. Merge into the unified classes (`pothole`, `speed_bump`)\nCheck the report: every source class must map to the right unified class.'),
    ('code', '!python scripts/merge_datasets.py --raw /content/raw --out /content/merged'),
    ('md', """## 6. Experiments
Run **one experiment per Colab session** (free sessions time out). Each new session: run steps 1–5 again (about 20 min), then one experiment below, then step 9 to download.

| Run | What changes | Time on a T4 | Status |
|---|---|---|---|
| v0_public_merge | baseline: 50 epochs, 640 px | ~1 h | ✅ done 29 Sep |
| v1_e150 | train longer: 150 epochs | ~3 h | ✅ done 30 Sep on Kaggle (mAP50 0.825) |
| v2_e150_960 | + bigger images (960 px) for small potholes | ~6 h, may need Colab Pro or 2 sessions | ✅ done 30 Sep on Kaggle (mAP50 0.837) |"""),
    ('md', '### 6a. v0 baseline (done, kept for reference; uncomment only to reproduce)'),
    ('code', '# !python scripts/train.py --data /content/merged/data.yaml --device 0 --batch 32 --epochs 50 --name v0_public_merge\n# !python scripts/evaluate.py --weights runs/v0_public_merge/weights/best.pt --device 0 --public-data /content/merged/data.yaml'),
    ('md', '### 6b. v1: 150 epochs\nThe baseline was still improving at epoch 50. `patience 30` stops early if nothing improves for 30 epochs.'),
    ('code', "import pathlib\nassert pathlib.Path('/content/merged/data.yaml').exists(), 'Run steps 3-5 (download + merge) in this session first.'\n"
             '!python scripts/train.py --data /content/merged/data.yaml --device 0 --batch 32 --epochs 150 --patience 30 --name v1_e150\n!python scripts/evaluate.py --weights runs/v1_e150/weights/best.pt --device 0 --public-data /content/merged/data.yaml'),
    ('md', '### 6c. v2: 150 epochs at 960 px\nHelps small, distant potholes, but runs about 2× slower on the device too; the Hailo speed test decides if it is usable.'),
    ('code', '# Run in its own session: uncomment both lines, and comment out the v1 cell above.\n# !python scripts/train.py --data /content/merged/data.yaml --device 0 --batch 16 --epochs 150 --patience 30 --imgsz 960 --name v2_e150_960\n# !python scripts/evaluate.py --weights runs/v2_e150_960/weights/best.pt --device 0 --imgsz 960 --public-data /content/merged/data.yaml'),
    ('md', '## 7. (Done) Learning curve\nAlready run on 29 Sep (25/50/75 %). Uncomment only to reproduce.'),
    ('code', '# for f in (0.25, 0.5, 0.75):\n#     !python scripts/train.py --data /content/merged/data.yaml --device 0 --batch 32 --epochs 50 --fraction {f}'),
    ('md', '## 8. Download the results\nTrained models, metrics, confusion matrices and merge report (not the dataset, not the clip videos). Unzip into `ICVSP/ai/` and run `python scripts/compare_runs.py` to add the run to `results/experiments.md`.'),
    ('code', """!cp /content/merged/merge_report.json runs/ 2>/dev/null; cd /content/ai && zip -qr /content/icvsp_results.zip runs -x 'runs/egypt_clips/*'
from google.colab import files
files.download('/content/icvsp_results.zip')"""),
    ('md', """## 9. Egyptian clips, part 1: visual check + pre-labels
**No GPU needed** (Runtime type *CPU* is fine, so it never hits the GPU quota). Run steps 1, 2 and 2b first, then this cell.

Name clips `<area>_<name>_<n>.mov` (e.g. `maadi_malak_1.mov`); the area is used to report results per place.
The cell downloads the trained models from GitHub, then:
1. draws the model's boxes on every clip → `egypt_clips_check.zip` (watch these for a first impression),
2. extracts 2 frames per second and pre-labels them → `prelabels.zip` (import into CVAT and correct, see part 2)."""),
    ('code', """import pathlib, shutil, urllib.request
from google.colab import files
%cd /content/ai
clips = pathlib.Path('data/egypt_test/clips'); clips.mkdir(parents=True, exist_ok=True)
print('Select your clips:')
for name in files.upload():
    shutil.move(name, clips / name)
BASE_URL = 'https://github.com/S2800-0/icvsp-prototype/raw/main/ai/models/'
pathlib.Path('models').mkdir(exist_ok=True)
for m in ('v1_e150.pt', 'v2_e150_960.pt'):
    if not pathlib.Path('models', m).exists():
        urllib.request.urlretrieve(BASE_URL + m, f'models/{m}')
# v2 (960 px) finds more potholes, so it gives the best starting boxes to correct
!python scripts/predict_clips.py --weights models/v2_e150_960.pt --imgsz 960 --conf 0.25
!python scripts/extract_frames.py --fps 2
!python scripts/prelabel.py --weights models/v2_e150_960.pt --imgsz 960
!cd runs && zip -qr /content/egypt_clips_check.zip egypt_clips
!cd data/egypt_test && zip -qr /content/prelabels.zip prelabels
files.download('/content/egypt_clips_check.zip')
files.download('/content/prelabels.zip')"""),
    ('md', """## 10. Egyptian clips, part 2: label, then measure
**Labelling (outside Colab), in [CVAT](https://app.cvat.ai), which keeps the task private** (clips show faces and number plates):
1. Create a task with labels exactly `pothole` and `speed_bump`, and upload the images from `prelabels.zip` (`images/train/`).
2. *Actions → Upload annotations → Ultralytics YOLO Detection 1.0* → select `prelabels.zip`.
3. Go through **every** frame: fix wrong boxes, delete false ones, **add missed bumps and potholes**. Empty frames stay empty.
4. *Export task dataset → Ultralytics YOLO Detection 1.0, with images* → download the zip.

Then run this cell and select that export zip. It builds the Egyptian test set and prints the decision:
**ENOUGH / TOP-UP / NOT ENOUGH** (thresholds fixed in advance: speed-bump recall ≥ 0.75 and precision ≥ 0.70)."""),
    ('code', """import pathlib, urllib.request
from google.colab import files
%cd /content/ai
BASE_URL = 'https://github.com/S2800-0/icvsp-prototype/raw/main/ai/models/'
pathlib.Path('models').mkdir(exist_ok=True)
for m in ('v1_e150.pt', 'v2_e150_960.pt'):
    if not pathlib.Path('models', m).exists():
        urllib.request.urlretrieve(BASE_URL + m, f'models/{m}')
print('Select the export zip from CVAT:')
export = next(iter(files.upload()))
!python scripts/prepare_egypt_test.py "{export}"
# both models: v1 (640 px, faster) and v2 (960 px, more accurate); each writes models/../evaluation.json, so keep copies
!python scripts/evaluate.py --weights models/v1_e150.pt --imgsz 640 --egypt-data data/egypt_test/data.yaml && cp evaluation.json evaluation_v1.json
!python scripts/evaluate.py --weights models/v2_e150_960.pt --imgsz 960 --egypt-data data/egypt_test/data.yaml && cp evaluation.json evaluation_v2.json
!cd /content/ai && zip -qr /content/egypt_eval.zip evaluation_v1.json evaluation_v2.json runs/eval_egypt_test_*
files.download('/content/egypt_eval.zip')"""),
]


# ---------------------------------------------------------------- Kaggle
KW = '/kaggle/working/ai'
KAGGLE_CELLS = [
    ('md', """# ICVSP: pothole & speed-bump detector on Kaggle

Runs **unattended**: click **Save Version → Save & Run All (Commit)**, close the browser, and come back later.
Everything in `/kaggle/working` (the trained model, metrics, plots and `icvsp_results.zip`) is kept in the version's **Output** tab.

**One-time setup** (right-hand panel → *Session options*):
- **Accelerator: GPU T4 x2**
- **Internet: On** (needs a phone-verified Kaggle account; used to install packages and download the public SBP-YOLO dataset)

Limits: about 30 GPU hours per week, 12 hours per run. v1 (0.825) and v2 (0.837) are done.
**Next run: v3**, which fine-tunes v2 on Egyptian / night frames plus synthetic night copies (about 3–4 h).

**v3 needs your labelled frames as a private Kaggle dataset** (never public: YouTube frames, faces, plates):
1. kaggle.com → *Datasets → New Dataset*, name it **icvsp-egypt-train**, keep it **Private**.
2. Upload the zips, one per batch, **named by kind**, because the name becomes the source folder:
   - `egypt_<name>.zip` or `youtube_<name>.zip`: CVAT exports (*Ultralytics YOLO Detection 1.0, with images*)
   - `background_<name>.zip`: hazard-free night frames (reflections, wet road); just images, no labels
3. In this notebook: *Add Input → Datasets → Your Datasets → icvsp-egypt-train*.

_Generated by `scripts/build_notebook.py`. Edit the files in `ICVSP/ai/` and regenerate; do not edit the embedded copies below._"""),
    ('md', """## Settings: the only cell to edit
- `EXPERIMENT`: which run to train.
- `RESUME_FROM`: leave empty for a fresh run. To continue a run that was cut off, attach the earlier version's output
  (*Add Input → Your Work → this notebook*) and paste the path to its `last.pt`, e.g.
  `/kaggle/input/<notebook-name>/ai/runs/v1_e150/weights/last.pt`."""),
    ('code', """EXPERIMENT = 'v3_egypt_night'  # done: v1_e150 mAP50 0.825, v2_e150_960 mAP50 0.837
RESUME_FROM = ''                # '' = fresh run, or the path to an interrupted run's last.pt
NIGHT_SHARE = 0.3               # v3: share of daytime train images that get a synthetic night copy (0 = off)

EXPERIMENTS = {
    'v1_e150':        '--batch 32 --epochs 150 --patience 30',
    'v2_e150_960':    '--batch 16 --epochs 150 --patience 30 --imgsz 960',
    # fine-tune: starts from the v2 weights, so fewer epochs are needed
    'v3_egypt_night': '--model models/v2_e150_960.pt --batch 16 --epochs 80 --patience 20 --imgsz 960',
}
assert EXPERIMENT in EXPERIMENTS, f'unknown experiment {EXPERIMENT}'
ARGS = EXPERIMENTS[EXPERIMENT]
IMGSZ = 640 if EXPERIMENT == 'v1_e150' else 960"""),
    ('md', '## 1. GPU and project folder'),
    ('code', f'!nvidia-smi -L\n%mkdir -p {KW}/scripts {KW}/configs {KW}/runs\n%cd {KW}'),
    ('md', '## 2. Project scripts'),
    *[('code', f'%%writefile {KW}/{f}\n' + (ROOT / f).read_text()) for f in EMBED],
    ('md', '## 3. Install packages'),
    ('code', f'!pip -q install -r {KW}/requirements.txt\nimport ultralytics; print("ultralytics", ultralytics.__version__, "installed")'),
    ('md', '## 4. Download SBP-YOLO, add the Egyptian / night data, merge\nThe data goes to `/tmp` so it is not saved into the output. Class IDs were verified on 29 Sep (0 = pothole, 1 = speed bump). The download is retried automatically if Drive rate-limits it. For v3, the zips from the private `icvsp-egypt-train` dataset are unpacked next to SBP-YOLO; video frames are split by video, never by frame.'),
    ('code', """import subprocess
for attempt in range(3):
    subprocess.run(['python', 'scripts/download_sbp.py', '--out', '/tmp/raw/sbp_yolo'], check=True)
    if not __import__('pathlib').Path('/tmp/raw/sbp_yolo/failed.txt').exists():
        break
    __import__('os').remove('/tmp/raw/sbp_yolo/failed.txt')
import glob, os, pathlib, urllib.request, zipfile
zips = sorted(glob.glob('/kaggle/input/icvsp-egypt-train/**/*.zip', recursive=True))
if EXPERIMENT.startswith('v3'):
    assert zips, 'v3 needs the private icvsp-egypt-train dataset attached (see the top of the notebook).'
    pathlib.Path('models').mkdir(exist_ok=True)
    urllib.request.urlretrieve('https://github.com/S2800-0/icvsp-prototype/raw/main/ai/models/v2_e150_960.pt',
                               'models/v2_e150_960.pt')
for z in zips:
    name = pathlib.Path(z).stem.lower()
    assert name.startswith(('egypt', 'youtube', 'background')), f'{z}: name it egypt_*, youtube_* or background_*'
    zipfile.ZipFile(z).extractall(f'/tmp/raw/{name}')
    print(name, sum(1 for _ in pathlib.Path(f'/tmp/raw/{name}').rglob('*.jpg')), 'images')
!python scripts/merge_datasets.py --raw /tmp/raw --out /tmp/merged
if EXPERIMENT.startswith('v3') and NIGHT_SHARE > 0:
    !python scripts/make_night.py --data /tmp/merged --share {NIGHT_SHARE}
!cp /tmp/merged/merge_report.json runs/"""),
    ('md', '## 5. Train\nA fresh run trains from the YOLO11n starting weights; a resumed run continues from `RESUME_FROM` with its original settings.'),
    ('code', """import pathlib, shutil
if RESUME_FROM:
    last = pathlib.Path(f'runs/{EXPERIMENT}/weights/last.pt')
    last.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy(RESUME_FROM, last)
    !python scripts/train.py --resume {last}
else:
    !python scripts/train.py --data /tmp/merged/data.yaml --device 0 {ARGS} --name {EXPERIMENT}"""),
    ('md', '## 6. Evaluate on the public test set'),
    ('code', '!python scripts/evaluate.py --weights runs/{EXPERIMENT}/weights/best.pt --device 0 --imgsz {IMGSZ} --public-data /tmp/merged/data.yaml'),
    ('md', '## 7. Package the results\n`icvsp_results.zip` appears in the version\'s **Output** tab. Download it, unzip into `ICVSP/ai/`, and run `python scripts/compare_runs.py` to add the run to the experiment log.'),
    ('code', f"!cd {KW} && zip -qr /kaggle/working/icvsp_results.zip runs && ls -lh /kaggle/working/icvsp_results.zip"),
]


def write(cells, name, meta):
    nb = {'cells': [], 'nbformat': 4, 'nbformat_minor': 4, 'metadata': meta}
    for kind, src in cells:
        cell = {'cell_type': 'markdown' if kind == 'md' else 'code', 'metadata': {}, 'source': src.splitlines(True)}
        if kind == 'code':
            cell.update(execution_count=None, outputs=[])
        nb['cells'].append(cell)
    (ROOT / name).write_text(json.dumps(nb, indent=1))
    print(f'{name}: {len(cells)} cells')


def main():
    py = {'name': 'python3', 'display_name': 'Python 3'}
    write(CELLS, 'ICVSP_train.ipynb', {'accelerator': 'GPU', 'colab': {'provenance': []}, 'kernelspec': py})
    write(KAGGLE_CELLS, 'ICVSP_train_kaggle.ipynb',
          {'kernelspec': py, 'kaggle': {'accelerator': 'nvidiaTeslaT4', 'isInternetEnabled': True, 'isGpuEnabled': True}})


if __name__ == '__main__':
    main()
