"""Build the experiment log: one table comparing every training run, plus its key plots.

Reads runs/<run>/results.csv, args.yaml and evaluation.json (if present) and writes
  results/experiments.csv   all numbers, for spreadsheets and the thesis
  results/experiments.md    readable table with the change versus the baseline
  results/<run>/            confusion matrix, PR curve and training curves of each run

Run it locally after unzipping a new icvsp_results.zip into ICVSP/ai/.
Usage:  python scripts/compare_runs.py [--baseline v0_public_merge]
"""
import argparse, csv, json, shutil
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
PLOTS = ['confusion_matrix_normalized.png', 'confusion_matrix.png', 'BoxPR_curve.png', 'results.png']


def val_metrics(run: Path):
    rows = [{k.strip(): v for k, v in r.items()} for r in csv.DictReader(open(run / 'results.csv'))]
    best = max(rows, key=lambda r: float(r['metrics/mAP50-95(B)']))
    return {'epochs_run': len(rows), 'best_epoch': int(float(best['epoch'])),
            'val_mAP50': float(best['metrics/mAP50(B)']), 'val_mAP50_95': float(best['metrics/mAP50-95(B)'])}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--baseline', default='v0_public_merge')
    a = ap.parse_args()
    out = ROOT / 'results'
    out.mkdir(exist_ok=True)
    rows = []
    for run in sorted(p for p in (ROOT / 'runs').iterdir() if (p / 'results.csv').exists()):
        args = yaml.safe_load((run / 'args.yaml').read_text())
        row = {'run': run.name, 'model': Path(str(args['model'])).stem, 'epochs': args['epochs'],
               'imgsz': args['imgsz'], 'data_fraction': args.get('fraction', 1.0), **val_metrics(run)}
        ev = run / 'evaluation.json'
        if ev.exists():
            e = json.loads(ev.read_text())
            pt = e.get('public_test')
            if isinstance(pt, dict):
                row['test_mAP50'] = pt['overall_mAP50']
                for cls, m in pt['per_class'].items():
                    row[f'test_{cls}_P'], row[f'test_{cls}_R'], row[f'test_{cls}_mAP50'] = m['precision'], m['recall'], m['mAP50']
            eg = e.get('egypt_test')
            if isinstance(eg, dict):
                row['egypt_speed_bump_R'] = eg['per_class'].get('speed_bump', {}).get('recall')
                row['egypt_speed_bump_P'] = eg['per_class'].get('speed_bump', {}).get('precision')
            row['decision'] = e.get('decision', '')
        rows.append(row)
        dst = out / run.name
        dst.mkdir(exist_ok=True)
        for src_dir in [run] + sorted((ROOT / 'runs').glob(f'eval_public_test_{run.name}')):
            for plot in PLOTS:
                if (src_dir / plot).exists():
                    prefix = 'test_' if src_dir != run else 'val_'
                    shutil.copy2(src_dir / plot, dst / f'{prefix}{plot}')

    cols = list(dict.fromkeys(k for r in rows for k in r))
    with open(out / 'experiments.csv', 'w', newline='') as f:
        w = csv.DictWriter(f, fieldnames=cols)
        w.writeheader(); w.writerows(rows)

    base = next((r for r in rows if r['run'] == a.baseline), None)
    show = ['run', 'epochs', 'imgsz', 'data_fraction', 'best_epoch', 'val_mAP50', 'test_mAP50',
            'test_speed_bump_P', 'test_speed_bump_R', 'test_pothole_P', 'test_pothole_R', 'egypt_speed_bump_R']
    show = [c for c in show if c in cols]
    fmt = lambda v: f'{v:.3f}' if isinstance(v, float) else ('' if v is None else str(v))
    lines = ['# ICVSP detector experiments', '',
             f'Generated by `scripts/compare_runs.py`. Baseline: `{a.baseline}`. '
             'val = validation split during training; test = public SBP-YOLO test split (1,104 images); '
             'egypt = labelled Egyptian clips. Δ = change versus baseline on test mAP50.', '',
             '| ' + ' | '.join(show + ['Δ test mAP50']) + ' |', '|' + '---|' * (len(show) + 1)]
    for r in rows:
        d = ''
        if base and 'test_mAP50' in r and 'test_mAP50' in base and r is not base:
            d = f"{r['test_mAP50'] - base['test_mAP50']:+.3f}"
        lines.append('| ' + ' | '.join(fmt(r.get(c)) for c in show) + f' | {d} |')
    lines += ['', 'Plots for each run are in `results/<run>/` (val_ = during training, test_ = public test).']
    (out / 'experiments.md').write_text('\n'.join(lines) + '\n')
    print('\n'.join(lines))


if __name__ == '__main__':
    main()
